# Generated by Django 3.0.7 on 2020-06-10 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_released',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date released'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=63),
        ),
    ]
