# Generated by Django 3.0.7 on 2020-06-10 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200610_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.CharField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
    ]
