# Generated by Django 3.0.7 on 2020-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.CharField(default='decription', max_length=500),
            preserve_default=False,
        ),
    ]
